# Just change the values as desired. No recommended to commit this file.
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
type: Opaque
data:
  secret_1: BASE_64_ENCODED_STRING # example: username
  secret_2: BASE_64_ENCODED_STRING # example: password